compatibility_date = "2024-12-24"
compatibility_flags = ["nodejs_compat_v2"]
main = "src/index.ts"
name = "hono-durable-websocket-exp"

[[migrations]]
new_classes = ["WebsocketDurableObject"]
tag = "v1"

[durable_objects]
bindings = [
  {name = "DO_WEBSOCKET", class_name = "WebsocketDurableObject"},
]
